### ISSUE TITLE
Onboarding 1. RAPID Data Storyboard. Workshop Checklist. Github Onboarding.

### ISSUE THREAD

**Issue by ChristinaB** [rapid-research/learning-resources#4]
Review: https://rapid-research.github.io/learning-resources/prep/github/
Make Updates here: https://github.com/rapid-research/learning-resources

**Comment by ChristinaB** [comment]
[Future tiktok video on the exciting world of more usernames and passwords](https://github.com/rapid-research/learning-resources/blob/master/videos/Github-Signup-MemberOrganization.mp4)

**Comment by ChristinaB** [comment]
- [ ] Activity Overview 
In this section of onboarding activities, you will spend 30 minutes and accomplish the following tasks:
- Get a User ID. 
- Add People to an Organization. Link to 90 sec video.
- Orientation to repository owners/members. Governance considerations. 

### Task List for 9/22 - 9/29 work
- [ ] Get a GithubID.  The only industries with 'Users' are addictive products and software. In our project, we have Content and Data Owners and Organization Members.  Hyperlink and update existing Github page with front material.  Link to 90 sec **video.**  
- [ ] Make a copy of the RAPID-research/learning-resources in your personal Github. For example, today there is a new repository in the world called  lshanley/learning-resources that tracks back to us and oceanhackweek.  
![image](https://user-images.githubusercontent.com/4108369/93935790-02e73b80-fcda-11ea-834c-702169cea688.png)




- [ ] Where do I find the invitation? There are two   Log in 
- [ ] Next agenda: Test half hour with Taina & Graciela 

- [ ] Zoom full screen exit and enter. Short-cuts: alt-f  and esc button

**Comment by ChristinaB** [comment]
Why use Github?
@faustman-crypto  Thanks for helping with initiating this list. 

1.  Begin https://github.com/rapid-research/learning-resources/issues/4

**Comment by ChristinaB** [comment]
@JillFalman 
documentation for this #1 Onboarding Workflow
- [ ] instruction for 30 min asynchoronous curriculum

- [ ] work with Elaine to use this issue to create a list of WHY GITHUB? as a section in Jurutungo module Github #1

**Comment by JillFalman** [comment]
I have a draft of "Why GitHub" and how to sign-up for a free account: 

# Why GitHub
GitHub is a web-based platform that hosts repositories of information. It provides a number of collaboration features for projects, including version control and task management. Repositories can contain source code in a variety of different programming languages (i.e. R, Python). The version control system allows users to keep track of constant revisions to code. Repositories can also contain additional documents (pdfs, Word, spreadsheets) and links to resources (e.g. videos). Each repository provides a community platform to view, improve, and derive new ideas from the uploaded code and documents.  

## GitHub Supporting Hurricane Research  
We are interested in sharing and accessing data from hurricane research. We also want to make resources available to researchers to better support data sharing. By using GitHub, we can make our results and processes more accessible. We want to learn from each other to be better prepared for Hurricanes. GitHub provides a community where we can collaborate and share research.  

## Introduction to GitHub
If you want to learn more about and how to start using GitHub, the program provides a free Learning Lab course.
https://lab.github.com/githubtraining/introduction-to-github 

# Set-up GitHub account
There are multiple videos and step-by-step guides available online. Below are two resource options to guide you through the process for setting-up your free GitHub account. 

To start, go to this website: https://github.com/join 

## Video Tutorial
Steps to sign-up for your GitHub account are shown in this video:
https://lambdaschool.com/the-commons/how-to-sign-up-for-a-free-github-account 

## Screenshot Tutorial
Steps to sign-up for your GitHub account are illustrated here: https://www.wikihow.com/Create-an-Account-on-GitHub 

### After Creating an Account
If you want to learn more about and how to start using GitHub, the program provides a free Learning Lab course.
https://lab.github.com/githubtraining/introduction-to-github

**Comment by faustman-crypto** [comment]
This is fantastic ! Please share. Elaine

**Comment by ChristinaB** [comment]
# Elements of a RAPID GeoHealth Case Study   

## RAPID Data Science: RAPID data management life cycle, Geohealth data governance 

## Earth Observation & Modeling:  

0: FAIR data   
1: Case Studies edge cases-end members   
2. Apply this expertise to your work OR Apply your expertise to this case study.

## Health: Prepare for Human Subjects Review (IRB)
             
## Network infrastructure: Github for Collaborative Research Teams, NSF Data Management Plan, UW IRB Awareness, 

Case Studies: Hurricane Maria, Field to Lab to Publication


 0. Elements 
     Cyberinfrastructure: 
     Human Subjects:
     Data Science:  G

 0. Dilemma

 0. Dialogue

**Comment by ChristinaB** [comment]
@GIRamirez this will give you a message in your email.  Click on it or the zoom link to get here.  Scroll to the bottom. Leave a comment.

**Comment by ChristinaB** [comment]
@GIRamirez owns 'i don't know'

**Comment by ChristinaB** [comment]
@ChristinaB 
By 10/8/2020
- [ ] update [Slido RAPID Quiz](https://app.sli.do/event/87pj4sv1)

**Comment by faustman-crypto** [comment]
Somethings are beginning to make sense and special thanks for this session.  I was able to access git-hub in a streamlined manner from my email  that was good news.  I am working with Jill to review sites and content.  Elaine

**Comment by GIRamirez** [comment]
Need to add Jurutungo to the terms list.
